// Namespaced tables can coexist with other features in the same database.
export const AWARDS_POSTGRES_SCHEMA = `
CREATE TABLE IF NOT EXISTS arena_award_receipts (
  sequence BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  id TEXT PRIMARY KEY,
  recipient TEXT NOT NULL,
  issuer TEXT NOT NULL,
  badge TEXT NOT NULL,
  week BIGINT,
  duplicate TEXT UNIQUE,
  data JSONB NOT NULL
);
CREATE INDEX IF NOT EXISTS arena_award_recipients ON arena_award_receipts(recipient);
CREATE INDEX IF NOT EXISTS arena_award_issuer_week ON arena_award_receipts(issuer, week);
CREATE TABLE IF NOT EXISTS arena_award_profiles (
  "user" TEXT PRIMARY KEY,
  choices JSONB NOT NULL DEFAULT '{}',
  worn JSONB NOT NULL DEFAULT '[]',
  revision INTEGER NOT NULL DEFAULT 0,
  checked BIGINT
);
ALTER TABLE arena_award_profiles ADD COLUMN IF NOT EXISTS seen JSONB NOT NULL DEFAULT '[]';
ALTER TABLE arena_award_profiles ADD COLUMN IF NOT EXISTS dismissed_notifications JSONB NOT NULL DEFAULT '[]';
CREATE TABLE IF NOT EXISTS arena_award_commands (id TEXT PRIMARY KEY, "user" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS arena_award_metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM arena_award_metadata WHERE key='visibility-v2') THEN
    UPDATE arena_award_profiles SET
      seen = (SELECT COALESCE(jsonb_agg(key), '[]'::jsonb) FROM jsonb_each_text(choices)),
      choices = (SELECT COALESCE(jsonb_object_agg(key, CASE WHEN value IN ('dismissed','hidden') THEN 'hidden' ELSE 'visible' END), '{}'::jsonb) FROM jsonb_each_text(choices));
    INSERT INTO arena_award_metadata VALUES ('visibility-v2','1');
  END IF;
END $$;
`;
